"""
Build a single JSON file for the Library Assessment dashboard.

This script combines the outputs generated by Stages 1–4 into one
dashboard-ready data file.
"""

from pathlib import Path
import json

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]

OUTPUT_DIR = ROOT / "outputs"

DASHBOARD_DIR = ROOT / "dashboard"

DASHBOARD_DIR.mkdir(
    exist_ok=True
)


def load_csv(filename):

    path = OUTPUT_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"Required output not found: {path}"
        )

    return pd.read_csv(path)


def main():

    # ---------------------------------------------------------
    # Stage 1
    # ---------------------------------------------------------

    stage1 = load_csv(
        "stage1_summary.csv"
    )

    student_level = load_csv(
        "satisfaction_by_student_level.csv"
    )

    # ---------------------------------------------------------
    # Stage 2
    # ---------------------------------------------------------

    theme_summary = load_csv(
        "theme_summary.csv"
    )

    sentiment_summary = load_csv(
        "sentiment_summary.csv"
    )

    with open(
        OUTPUT_DIR / "nlp_model_metrics.json",
        "r",
        encoding="utf-8",
    ) as file:

        nlp_metrics = json.load(file)

    # ---------------------------------------------------------
    # Stage 3 / 4
    # ---------------------------------------------------------

    with open(
        OUTPUT_DIR / "ai_v2_evaluation_summary.csv",
        "r",
        encoding="utf-8",
    ) as file:

        # This file is CSV, so pandas is easier.
        pass

    ai_v2_summary = load_csv(
        "ai_v2_evaluation_summary.csv"
    )

    ai_confidence = load_csv(
        "ai_v2_confidence_analysis.csv"
    )

    ai_errors = load_csv(
        "ai_v2_classification_errors.csv"
    )

    # ---------------------------------------------------------
    # V1 evaluation
    # ---------------------------------------------------------

    ai_v1_results = load_csv(
        "ai_analysis_results.csv"
    )

    v1_valid = ai_v1_results[
        ai_v1_results["valid_json"] == True
    ].copy()

    v1_accuracy = (
        (
            v1_valid["theme"]
            == v1_valid["validation_theme"]
        )
        .mean()
    )

    # ---------------------------------------------------------
    # Prompt comparison
    # ---------------------------------------------------------

    prompt_comparison = [
        {
            "version": "V1",
            "accuracy": round(
                float(v1_accuracy),
                4,
            ),
            "structured_output_rate": round(
                float(
                    ai_v1_results[
                        "valid_json"
                    ].mean()
                ),
                4,
            ),
            "macro_f1": 0.796,
        },
        {
            "version": "V2",
            "accuracy": float(
                ai_v2_summary[
                    "theme_accuracy"
                ].iloc[0]
            ),
            "structured_output_rate": float(
                ai_v2_summary[
                    "structured_output_rate"
                ].iloc[0]
            ),
            "macro_f1": float(
                ai_v2_summary[
                    "macro_f1"
                ].iloc[0]
            ),
        },
    ]

    # ---------------------------------------------------------
    # Model comparison
    # ---------------------------------------------------------

    model_comparison = [
        {
            "approach": (
                "TF-IDF + Logistic Regression"
            ),
            "accuracy": 0.947,
            "macro_f1": 0.948,
        },
        {
            "approach": (
                "Qwen2.5-1.5B — Prompt V1"
            ),
            "accuracy": round(
                float(v1_accuracy),
                4,
            ),
            "macro_f1": 0.796,
        },
        {
            "approach": (
                "Qwen2.5-1.5B — Prompt V2"
            ),
            "accuracy": float(
                ai_v2_summary[
                    "theme_accuracy"
                ].iloc[0]
            ),
            "macro_f1": float(
                ai_v2_summary[
                    "macro_f1"
                ].iloc[0]
            ),
        },
    ]

    # ---------------------------------------------------------
    # Final dashboard object
    # ---------------------------------------------------------

    dashboard_data = {

        "overview": {
            "total_responses": int(
                stage1.loc[
                    stage1["metric"]
                    == "Total responses",
                    "value",
                ].iloc[0]
            ),
            "overall_satisfaction": float(
                stage1.loc[
                    stage1["metric"]
                    == "Average satisfaction",
                    "value",
                ].iloc[0]
            ),
            "digital_resources": float(
                stage1.loc[
                    stage1["metric"]
                    == "Average digital resources score",
                    "value",
                ].iloc[0]
            ),
            "study_space": float(
                stage1.loc[
                    stage1["metric"]
                    == "Average study space score",
                    "value",
                ].iloc[0]
            ),
            "research_support": float(
                stage1.loc[
                    stage1["metric"]
                    == "Average research support score",
                    "value",
                ].iloc[0]
            ),
            "nlp_accuracy": 0.947,
            "ai_v2_accuracy": float(
                ai_v2_summary[
                    "theme_accuracy"
                ].iloc[0]
            ),
            "ai_v2_reliability": float(
                ai_v2_summary[
                    "structured_output_rate"
                ].iloc[0]
            ),
        },

        "student_level": (
            student_level
            .reset_index()
            .to_dict(
                orient="records"
            )
        ),

        "theme_summary": (
            theme_summary
            .to_dict(
                orient="records"
            )
        ),

        "sentiment_summary": (
            sentiment_summary
            .to_dict(
                orient="records"
            )
        ),

        "model_comparison": model_comparison,

        "prompt_comparison": (
            prompt_comparison
        ),

        "confidence": (
            ai_confidence
            .to_dict(
                orient="records"
            )
        ),

        "errors": (
            ai_errors
            .to_dict(
                orient="records"
            )
        ),

        "nlp_metrics": nlp_metrics,

    }

    output_file = (
        DASHBOARD_DIR
        / "dashboard_data.json"
    )

    with open(
        output_file,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            dashboard_data,
            file,
            indent=2,
        )

    print()
    print(
        "Dashboard data generated successfully."
    )

    print(
        f"Saved to: {output_file}"
    )


if __name__ == "__main__":
    main()